export const DISPLAY_LIBRARIES = 'DISPLAY_LIBRARIES';
export const SELECT_LIBRARY = 'SELECT_LIBRARY';

export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';

export const LOGIN_USER_STARTS = 'LOGIN_USER_STARTS';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';
