export const UPDATE_EMPLOYEE_FIELD = 'UPDATE_EMPLOYEE_FIELD';
export const ADD_EMPLOYEE_STARTS = 'ADD_EMPLOYEE_STARTS';
export const ADD_EMPLOYEE_SUCCESS = 'ADD_EMPLOYEE_SUCCESS';
export const ADD_EMPLOYEE_FAILED = 'ADD_EMPLOYEE_FAILED';
export const FETCH_EMPLOYEES_STARTS = 'FETCH_EMPLOYEES_STARTS';
export const FETCH_EMPLOYEES_SUCCESS = 'FETCH_EMPLOYEES_SUCCESS';
export const FETCH_EMPLOYEES_FAILED = 'FETCH_EMPLOYEES_FAILED';
export const EDIT_EMPLOYEE_STARTS = 'EDIT_EMPLOYEE_STARTS';
export const EDIT_EMPLOYEE_SUCCESS = 'EDIT_EMPLOYEE_SUCCESS';
export const EDIT_EMPLOYEE_FAILED = 'EDIT_EMPLOYEE_FAILED';
export const REMOVE_EMPLOYEE_STARTS = 'REMOVE_EMPLOYEE_STARTS';
export const REMOVE_EMPLOYEE_SUCCESS = 'REMOVE_EMPLOYEE_SUCCESS';
export const CLEAR_EMPLOYEE_STATE = 'CLEAR_EMPLOYEE_STATE';

export const DISPLAY_LIBRARIES = 'DISPLAY_LIBRARIES';
export const SELECT_LIBRARY = 'SELECT_LIBRARY';

export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';

// use in redux-sage
export const INICIATE_LOGIN_USER = 'INICIATE_LOGIN_USER';
//
export const LOGIN_USER_STARTS = 'LOGIN_USER_STARTS';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';
